export const Data = [
    {"id": "1000","features": "BSP Integration","feature_owner":"Aravind","function": "Integration","domain":"Linux Driver","description": "Product Description","image": "bamboo-watch.jpg","status": "ON", "mode":"Medium", "category": "Accessories","function_owner": "Horizontal","inventoryStatus": "INSTOCK","rating": 5,"estimation_type":"HC","q1":1, "q2":0.25, "q3":0.5, "q4":1},
    {"id": "1001","features": "Triage/CI","function": "Integration", "feature_owner":"Aravind","domain":"Linux Driver","description": "Product Description","image": "black-watch.jpg","status": "ON","mode":"Medium","category": "Accessories","function_owner": "Horizontal","inventoryStatus": "INSTOCK","rating": 4, "estimation_type":"HC","q1":1, "q2":0.25, "q3":0.5, "q4":1},
    {"id": "1002","features": "Kernel","function": "Kernel","feature_owner":"Paul Mei","domain":"Linux Driver","description": "Product Description","image": "blue-band.jpg","status": "ON","mode":"Medium","category": "Fitness","function_owner": "Validation","inventoryStatus": "LOWSTOCK","rating": 3, "estimation_type":"HC","q1":1, "q2":0.25, "q3":0.5, "q4":1},
    {"id": "1003","features": "Integration","function": "Integration","feature_owner":"Aravind","domain":"Windows Server","description": "Product Description","image": "blue-t-shirt.jpg","status": "ON","mode":"Medium","category": "Clothing","function_owner": "Validation","inventoryStatus": "INSTOCK","rating": 5,"estimation_type":"HC","q1":1, "q2":0.25, "q3":0.5, "q4":1},
    {"id": "1004","features": "Triage/CI","function": "Integration","feature_owner":"Aravind","domain":"Windows Server","description": "Product Description","image": "bracelet.jpg","status": "ON","mode":"Medium","category": "Accessories","function_owner": "Validation","inventoryStatus": "INSTOCK","rating": 4,"estimation_type":"HC","q1":1, "q2":0.25, "q3":0.5, "q4":1},
    {"id": "1005","features": "Q&R","function": "Core Team","feature_owner":"Ravi","domain":"Core Team","description": "Product Description","image": "brown-purse.jpg","status": "ON","mode":"Medium","category": "Accessories","function_owner": "Validation","inventoryStatus": "OUTOFSTOCK","rating": 4,"estimation_type":"HC","q1":1, "q2":0.25, "q3":0.5, "q4":1},
    {"id": "1006","features": "Remote Board Farm HC","function": "ADA","feature_owner":"Dinesh","domain":"ADA","description": "Product Description","image": "chakra-bracelet.jpg","status": "ON","mode":"Medium","category": "Accessories","function_owner": "Development","inventoryStatus": "LOWSTOCK","rating": 3,"estimation_type":"BTI","q1":1, "q2":0.25, "q3":0.5, "q4":1},
    {"id": "1007","features": "DevOps HC - Windows Server","function": "ADA","feature_owner":"Dinesh","domain":"ADA","description": "Product Description","image": "galaxy-earrings.jpg","status": "ON","mode":"Medium","category": "Accessories","function_owner": "Development","inventoryStatus": "INSTOCK","rating": 5,"estimation_type":"BTI","q1":1, "q2":0.25, "q3":0.5, "q4":1},
    {"id": "1008","features": "Automation Framework HC - Yocto","function": "ADA","feature_owner":"Dinesh","domain":"ADA","description": "Product Description","image": "game-controller.jpg","status": "ON","mode":"Medium","category": "Electronics","function_owner":"Development" ,"inventoryStatus": "LOWSTOCK","rating": 4,"estimation_type":"BTI","q1":1, "q2":0.25, "q3":0.5, "q4":1},
    {"id": "1009","features": "Automation Framework HC - Windows Server","function": "ADA","feature_owner":"Dinesh","domain":"ADA","description": "Product Description","image": "gaming-set.jpg","status": "ON","mode":"Medium","category": "Electronics","function_owner": "Development","inventoryStatus": "INSTOCK","rating": 3,"estimation_type":"BTI","q1":1, "q2":0.25, "q3":0.5, "q4":1}
]